sources:
  - title: "Google Japan Blog"
    url: "https://japan.googleblog.com/feeds/posts/default"
  - title: "Google Cloud Blog"
    url: "https://blog.google/products/google-cloud/rss/"
  - title: "Google Developers Blog"
    url: "https://developers.googleblog.com/feeds/posts/default"
  - title: "Google AI Blog"
    url: "https://feeds.feedburner.com/blogspot/gJZg"   
  - title: "Chrome Releases"
    url: "https://chromereleases.googleblog.com/feeds/posts/default"
  - title: "Chromium Releases"
    url: "https://blog.chromium.org/atom.xml"
  - title: "DeepMind"
    url: "https://deepmind.com/blog/feed/basic/"
  - title: "Google Research Blog"
    url: "https://feeds.feedburner.com/blogspot/gJZg"
  - title: "Android Developers Blog"
    url: "https://feeds.feedburner.com/blogspot/hsDu"
  - title: "The OpenAI Blog"
    url: "https://openai.com/news/rss.xml"
  - title: "Apple Developers"
    url: "https://developer.apple.com/jp/news/rss/news.rss"
  - title: "web.dev"
    url: "https://web.dev/feed.xml"
  - title: "GitHub Actions Changelog"
    url: "https://github.blog/changelog/label/actions/feed/"
  - title: "Gemini CLI Releases"
    url: "https://github.com/google-gemini/gemini-cli/releases.atom"
  - title: "Chrome Devtools MCP Releases"
    url: "https://github.com/ChromeDevTools/chrome-devtools-mcp/releases.atom"
  - title: "Playwright Releases"
    url: "https://github.com/microsoft/playwright/releases.atom"
  - title: "Playwright CLI Releases"
    url: "https://github.com/microsoft/playwright-cli/releases.atom"
  - title: "Playwright MCP Releases"
    url: "https://github.com/microsoft/playwright-mcp/releases.atom"
  - title: "freee Developers Hub"
    url: "https://developers.freee.co.jp/feed"
  - title: "M3 Tech Blog"
    url: "https://www.m3tech.blog/feed"
  - title: "DeNA Engineering on DeNA Engineering"
    url: "https://engineering.dena.com/index.xml"
  - title: "LINEYahoo Tech Blog"
    url: "https://techblog.lycorp.co.jp/ja/feed/index.xml"
  - title: "Mercari Engineers Blog"
    url: "https://engineering.mercari.com/blog/feed.xml"
  - title: "ZOZO TECH BLOG"
    url: "https://techblog.zozo.com/feed"
  - title: "DevelopersIO"
    url: "https://dev.classmethod.jp/feed/"
  - title: "G-gen Blog"
    url: "https://blog.g-gen.co.jp/feed"
  - title: "Future Architect Blog"
    url: "https://future-architect.github.io/atom.xml"
  - title: "NTT docomo Business Engineers Blog"
    url: "https://engineers.ntt.com/feed"
  - title: "IIJ Engineers Blog"
    url: "https://eng-blog.iij.ad.jp/feed"
  - title: "Cybozu productivityweekly"
    url: "https://zenn.dev/topics/productivityweekly/feed"
  - title: "MIXI DEVELOPERS Tech Blog"
    url: "https://zenn.dev/p/mixi/feed"
  - title: "NTT DATA TECH"
    url: "https://zenn.dev/p/nttdata_tech/feed"
  - title: "Ubie Tech Blog"
    url: "https://zenn.dev/p/ubie_dev/feed"
  - title: "Azukiazusa Tech Blog"
    url: "https://azukiazusa.dev/rss.xml"
  - title: "Nyosegawa HP"
    url: "https://nyosegawa.com/feed.xml"
  - title: "Google Cloud Tech ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCJS9pqu9BzkAMNTmzNMNhvg"
  - title: "Anthropic ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCrDwWp7EBBv4NwvScIpBDOA"
  - title: "Claude ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCV03SRZXJEz-hchIAogeJOg"    
  - title: "CyberAgent Developers ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYvmsuoQ32tVY6MpOYhr5jA"
  - title: "DeNATech ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSUmegspCR8k4s58-IEgFqg"
  - title: "UIT ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC9n_V1i4eumiKldJvQ3t6WA"
  - title: "Mercari Gears ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC_pA9s23xE9MXnN_SJQnL4g"
  - title: "Math BUllet ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCq4tFx2rHBAkcvKDTXrPcDw"
  - title: "TECH WORLD ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCISDrqLMNq3w9AZ4otdoRuA"
  - title: "Moozaru ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCLPHXwLp90A5R69Eltxo-sg"
  - title: "Show int ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCpO3RcIrPaDJJ0Q3cbZrvZA"
  - title: "OSPN.jp ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCEPkrGMghsXnoG1LffgjMJg"
  - title: "Academind ch"
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSJbGtTlrDami-tDGPUV9-w"
